name: Docker Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: gresakm/coder-image:java_development
